### ISSUE TITLE
Addition of another popular symmetric algorithm : Twofish

### ISSUE THREAD

**Issue by DragonDare** [Tech-Matrix/Cryptographic-Tool#7]
**Is your feature request related to a problem? Please describe.**
Not a problem, just a suggestion for adding another widely used algorithm to the given list.

**Describe the solution you'd like**
The list has hashing algorithms present (MD5) but missing out on encryption algotithms. Twofish would be a good addition in that sense.

**Describe alternatives you've considered**
Was considering AES (Advanced Encryption Algorithm) which is the current military standard in encryption algos but Twofish is fine for now.

**Additional context**
--

**Comment by charvibannur** [comment]
You've been assigned.
